add_test( [==[Adds two numbers]==] /app/rhayader_tests [==[Adds two numbers]==]  )
set_tests_properties( [==[Adds two numbers]==] PROPERTIES WORKING_DIRECTORY /app)
add_test( [==[Function definition and call]==] /app/rhayader_tests [==[Function definition and call]==]  )
set_tests_properties( [==[Function definition and call]==] PROPERTIES WORKING_DIRECTORY /app)
add_test( [==[Math module usage]==] /app/rhayader_tests [==[Math module usage]==]  )
set_tests_properties( [==[Math module usage]==] PROPERTIES WORKING_DIRECTORY /app)
add_test( [==[String module usage]==] /app/rhayader_tests [==[String module usage]==]  )
set_tests_properties( [==[String module usage]==] PROPERTIES WORKING_DIRECTORY /app)
add_test( [==[Array module usage]==] /app/rhayader_tests [==[Array module usage]==]  )
set_tests_properties( [==[Array module usage]==] PROPERTIES WORKING_DIRECTORY /app)
set( rhayader_tests_TESTS [==[Adds two numbers]==] [==[Function definition and call]==] [==[Math module usage]==] [==[String module usage]==] [==[Array module usage]==])
